package anonymized.shadedetector;

public enum ProcessingStage {
    QUERY_RESULTS,
    CONSOLIDATED_QUERY_RESULTS,
    VALID_POM,
    NO_DEPENDENCY_TO_VULNERABLE,
    SOURCES_FETCHED,
    SOURCES_EXPANDED,
    SOURCES_HAVE_JAVA_FILES,
    CLONE_DETECTED,
    POV_INSTANCE_COMPILED,
    POV_INSTANCE_SUREFIRE_REPORTS_GENERATED,
    POV_INSTANCE_VULNERABILITY_CONFIRMED,
    POV_INSTANCE_VULNERABILITY_CONFIRMED_SHADED
}
